import fs from "node:fs";
import path from "node:path";

const dir = path.join(__dirname, "..", "migrations");
const files = fs
  .readdirSync(dir)
  .filter((file) => file.endsWith(".sql"))
  .sort();
const migrations = files.map((file) => ({
  id: file.replace(/\.sql$/, ""),
  statements: fs
    .readFileSync(path.join(dir, file), "utf8")
    .split("--> statement-breakpoint")
    .map((statement) => statement.trim())
    .filter(Boolean),
}));
const generated = `// generated by scripts/embed-migrations.ts — run \`pnpm db:generate\`, do not edit
export const migrations: { id: string; statements: string[] }[] = ${JSON.stringify(migrations, null, 2)};
`;
fs.writeFileSync(path.join(__dirname, "..", "src", "migrations.gen.ts"), generated);
